/*
-- Query: SELECT * FROM newschema.slu19roster
LIMIT 0, 50000

-- Date: 2025-02-07 16:40
*/
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('FIRST NAME','SURNAME','DATE OF BIRTH','POSITION');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Manouel','Kalafatis','23/3/2005','Goalkeeper');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Georgios','Manousakis','21/5/2006','Goalkeeper');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Dimitris','Kappas','30/5/2007','Goalkeeper');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Stiven','Buscokaj','14/4/2007','Goalkeeper');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Emanouil','Charalampakis','14/5/2007','Defender');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Konstantinos','Lagoudakis','	03/02/2008','Defender');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Ilias','Simantirakis','22/12/2005','Defender');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Pavlos','Kenourgiakis','6/3/2008','Defender');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Nikolaos','Ninirakis','25/1/2007','Defender');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Ali Ahmed','	Al-Sarif','	23/07/2005','Defender');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Savvas','Balasis','	07/04/2008','Defender');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Nikiforos','Beinas','	21/09/2007','Defender');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Stefanos','Darlas','27/6/2007','Midfielder');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Nikolaos','Stavropoulos','	09/05/2006','Midfielder');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('Emanouel','Chinaris','	24/03/2008','Midfielder');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('','','','');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PANETOLIKOS ROSTER 2024-2025','','','');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('FIRST NAME','SURNAME','DATE OF BIRTH','POSITION');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KONSTANTINOS','IOAKIMIDIS','19.05.2007','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ILIAS','GKOGKAKIS','08.10.2007','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXIOS','KITSOS','27.09.2007','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('EFTHIMIOS','PAPAZOIS','06.09.2007','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('NIKOLAOS','ADAMOPOULOS','27.06.2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('DAVID','GALIATSOS','01.02.2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('VASILIOS','DRAKOPOULOS','12.09.2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PANAGIOTIS','KAPSIS','10.02.2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('THEOCHARIS','LOLOUDIS','02.02.2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('CHRYSOVALANTIS','MANOS','01.06.2005','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KONSTANTINOS','MOKKAS','14.03.2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KONSTANTINOS','DALIANIS','02.10.2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','TSORIS','09.11.2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('AGGELOS','KARANTALIS','08.10.2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('STYLIANOS','KECHAGIAS','10.03.2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','KYRIAZIS','14.03.2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('STYLIANOS','MAVROS','25.04.2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('CHRISTOS','PAVLIDIS','04.02.2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PANAGIOTIS','PISTIKOS','14.08.2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('VASILIOS','RADOS','26.05.2005','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('SOTIRIOS','KONTOURIS','24.02.2005','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('EVANGELOS','NIKOLAOU','03.06.2004','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ARISTIDIS','ALBANIS','01.06.2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('EFTHIMIOS','GIOTOPOULOS','24.01.2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('CHRISTOS','ESKENTZIS','18.08.2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('VASILIOS','KAKIONIS','12.11.2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','PANAGIOTAKIS','04.03.2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('IOANNIS','TSIRIMOKOS','16.07.2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('DAVID','HOXHA','20.07.2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('','','','');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ARIS ROSTER 2024-2025','','','');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('FIRST NAME','SURNAME','DATE OF BIRTH','POSITION');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KONSTANTINOS','KOUTROULIDIS','1/6/2006','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('CHRISTOS','GEORGIADIS','','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('EMILIANO','KARAJ','19/9/2005','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KONSTANTINOS','ATREIDIS','13/07/2007','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PETROS','BABLIKOU','9/5/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','DAOULARIS','29/3/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('VASILIOS','PEITSIS','23/2/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ORESTIS','KOULA','4/2/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','SITARAS','14/7/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KORONAIOS','SEVASTIDIS','19/1/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('DENADRO','LALA','17/10/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('OZER','MEMETOGLOU','1/3/2005','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('CHRISTOS','TOTSIKAS','1/6/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('NIKOLAOS','MAVRIDIS','23/1/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('APOSTOLOS','PASCHALIDIS','17/7/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','KAZANTZIDIS','6/5/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXANDROS','SEFA','6/10/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('CHRISTOS','GEORGIOU','20/5/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KONSTANTINOS','CHAROUPAS','21/9/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PAVLOS','GEORGIOU','20/8/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KONSTANTINOS','KONTONIKOLAOU','26/1/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PANAGIOTIS','DIMITRAKOPOULOS','1/5/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXANDROS','VERIDIANO','4/8/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXANDROS','VERGAS','3/1/2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXANDROS','CHOCHLAKIS','30/1/2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PETROS','KARAKOSTAS','27/2/2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEKOS','KARAMANLIS','7/2/2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PANAGIOTIS','ZISOPOULOS','4/2/2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('MAXIMOS','ROUTSIS','','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','BAKAS','3/3/2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ERIDO','KLOGRI','31/7/2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('NIKOLAOS','PALASKAS','20/8/2007','');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('','','','');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PANATHINAIKOS FC U19 ROSTER SEASON 2024/2025','','','');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('FIRST NAME','SURNAME','DATE OF BIRTH','POSITION');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('IOANNIS','MPONOVAS','5/2/2007','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ATHANASIOS','ZOGAS','5/10/2007','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXANDROS','PAPAPOSTOLOU','21/2/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('AGGELOS','VYNTRA','28/2/2008','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('IOANNIS','LINARDAKIS','28/2/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('IASONAS','SKARLATIDIS','4/8/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('MICHAIL','KAROUZOS','25/4/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('NEKTARIOS','KALOSKAMIS','10/1/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('NIKOLAOS','NIKOLETOPOULOS','10/8/2005','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('SERAFIM','CHANTZARAS','13/1/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('SOTIRIOS','DOUVIKAS','10/2/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ZAHARIAS','VENAKIS','28/6/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ANDRIANO','BREGU','9/4/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXIS','OUZOUNIDIS','27/7/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','APOSTOLOU','22/6/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('IOANNIS','MPOKOS','3/2/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('IOANNIS','TAKESHIAN','24/12/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('MARKOS','SPATHARIS','18/8/2005','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PETROS','KOLOKOTRONIS','21/12/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ROUSIT','ZEKA','28/2/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('STYLIANOS','BEVARDOS','23/1/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('THOMAS','MARKEZINIS','13/8/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ATHANASIOS','PANOS','20/7/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('DIMITRIOS','ANDRIOTIS','25/5/2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','SOKOS','25/1/2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('MAMADOU','DIALLO','4/2/2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('NIKOLAOS','TRIKATZIS','10/1/2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ODYSSEAS','LAZARIS','26/11/2005','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('SOTIRIOS','TERZIS','11/8/2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('','','','');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PANSERRAIKOS FC U19 ROSTER - 2024/2025 SEASON','','','');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('FIRST NAME','SURNAME','DATE OF BIRTH','POSITION');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('NIKOS','APOSTOLAKIS','23/2/2006','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('MANOLIS','KAPLANIDIS','20/4/2007','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('THODORIS','XINAKIS','24/1/2007','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('FOTIS','CHAVOS','18/1/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('LEFTERIS','PAPADOPOULOS','24/10/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('`THANASIS','POUGKAS','11/2/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('TRYFON','KALIOGLOU','23/3/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('THOMAS','MAGIS','11/2/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('VASILIS','GKIOLAS','4/11/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PETROS','MPLATSIOTIS','16/5/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('EYRIPIDIS','FTHETAKIS','8/10/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('STAVROS','VASILAKOS','19/9/2008','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GIANNIS','KOSMIDIS','26/11/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KONSTANTINOS','GOURIDIS','21/5/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('DENIS','SHERA','5/7/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ZANIS','TSAGKARAKIS','17/8/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('NIKOS','THEOFILOU','30/4/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('LAZAROS','ELEFTHERIADIS','23/10/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('STEFANOS','ALEIFEROPOULOS','4/2/2005','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KONSTANTINOS','MAVROPOULOS','13/1/2005','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXANDROS','SALVANOS','19/9/2008','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KARIM','HAMED','19/9/2005','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('AGGELOS','TRIANTAFILOU','22/5/2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('NIKOS','TOLIOS','22/6/2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('CHARALAMPOS','KOSMOPOULOS','9/4/2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GIORGOS','GEORGOYLAKIS','14/4/2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('AGGELOS','MISSAS','5/1/2006','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('EPAMINONDAS','KOTIDIS','16/1/2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KNAJ','YOUSHAA','25/11/2005','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('','','','');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('OLYMPIACOS FC U19 ROSTER 2024/2025 SEASON','','','');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('FIRST NAME','SURNAME','DATE OF BIRTH','POSITION');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','KOURAKLIS','27/6/2005','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('IASONAS','GEORGAGOKOPOULOS','16/2/2007','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXANDROS','EXARCHOS','2/6/2005','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ANASTASIOS','KABAGIOVANIS','20/6/2007','GOALKEEPER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','FRAGOS','22/5/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PARASKEVAS','PLEOINIS','19/10/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ILIAS','PANAGAKOS','22/7/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KONSTANTINOS','TANOULIS','7/3/2005','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('VASILEIOS','KARKATSALIS','10/4/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ANTONIS','DAMA','19/1/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('VASILEIOS','PREKATES','298/2005','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('NEKTARIOS','ALAFAKIS','13/3/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ILIAS','GIOTOPOULOS','11/2/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('GEORGIOS','KOUTSOPOULOS','13/3/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('SAVVAS','SKOUROPOULOS','7/2/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('IOANNIS','ROLAKIS','13/3/2006','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('STELIO','SOULANIAKOU','11/6/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXANDROS','THEODORIDIS','24/4/2007','DEFENDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('APOSTOLOS','FLOYDAS','5/1/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('CHRISTOS','FILIS','25/6/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('KONSTANTINOS','PLISH','1/5/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('CHRISTOS-EFRAIM','DARVIRAS','11/1/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('SARANTOS','VASILAKOPOULOS','1/8/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ARGYRIOS','LIATSIKOURAS','20/12/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('CHRISTOS','LIGDAS','12/10/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('CHRISTOS','MICHAILIDIS','12/7/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('VASILEIOS','KTENAS','23/2/2007','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('STAVROS','PNEVMONIDIS','7/8/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ATHANASIOS','STANTZOS','21/3/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('PASCHALIS','TOUFAKIS','12/9/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('NIKOLAOS','LOLIS','20/1/2005','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('TAIYE','YUSUF','2/1/2006','MIDFIELDER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXANDROS','TZAMALIS','20/6/2007','ATTACKER');
INSERT INTO `` (`OFI CRETE ROSTER 2024-25`,`MyUnknownColumn`,`MyUnknownColumn_[0]`,`MyUnknownColumn_[1]`) VALUES ('ALEXANDROS','SUFKA','21/4/2006','ATTACKER');
